global:
  smtp_from: prometheus@localhost
  smtp_smarthost: 192.168.68.127:25
  smtp_require_tls: false

route:
  receiver: email

receivers:
  - name: email
    email_configs:
      - to: pi@localhost
        send_resolved: true
inhibit_rules:
  - target_match:
      alertname: http_down
    source_match:
      alertname: node_down
    equal: ['host']
  - target_match:
      alertname: SSLCertExpiringSoon
    source_match:
      alertname: http_down
    equal: ['instance']
