version: '3'
volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  prom:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    links:
      - alertmanager:alertmanager
    networks:
      prom:
        ipv4_address: 172.30.0.2
    restart: always
  alertmanager:
    container_name: prometheus-alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    networks:
      prom:
        ipv4_address: 172.30.0.3
    restart: always
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      prom:
        ipv4_address: 172.30.0.4
    restart: always
